//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_stdcost
    {
        public int ID { get; set; }
        public string acc_partnum { get; set; }
        public string acc_desxit { get; set; }
        public double acc_baspit { get; set; }
        public double acc_cost { get; set; }
    }
}
