//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity_log
    {
        public int ID { get; set; }
        public int product_id { get; set; }
        public string us_NAME { get; set; }
        public string benchmark { get; set; }
        public string result { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public string description { get; set; }
        public string partOf { get; set; }
    }
}
