//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_log
    {
        public int log_ID { get; set; }
        public string log_tbl { get; set; }
        public string log_col { get; set; }
        public string log_user { get; set; }
        public string log_was { get; set; }
        public string log_is { get; set; }
        public System.DateTime log_date { get; set; }
    }
}
