//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class fb_lib
    {
        public int fb_ID { get; set; }
        public string fb_com { get; set; }
        public string fb_fiber { get; set; }
        public string fb_consaccy { get; set; }
        public string fb_colorprt { get; set; }
        public string fb_finishing { get; set; }
        public Nullable<double> fb_fwsize { get; set; }
        public string fb_moq { get; set; }
        public Nullable<int> fb_lt { get; set; }
        public string fb_uom { get; set; }
        public Nullable<double> fb_price { get; set; }
        public string fb_vendor { get; set; }
        public string fb_desc { get; set; }
        public string fb_remark { get; set; }
        public Nullable<int> fb_agisbx { get; set; }
        public Nullable<double> fb_agprice { get; set; }
        public string fb_actvt { get; set; }
    }
}
