//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class fep_qa
    {
        public string feq_Asst { get; set; }
        public string feq_Toy { get; set; }
        public string feq_Parent { get; set; }
        public string feq_Child { get; set; }
        public Nullable<int> feq_Level { get; set; }
        public string feq_ler { get; set; }
        public string feq_remark { get; set; }
        public string feq_refer { get; set; }
        public int feq_qa_id { get; set; }
    }
}
