//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class fep_dsa
    {
        public string fep_Asst { get; set; }
        public string fep_Toy { get; set; }
        public string fep_Parent { get; set; }
        public string fep_Child { get; set; }
        public string fep_Desc { get; set; }
        public Nullable<int> fep_Level { get; set; }
        public string fep_ProcessChild { get; set; }
        public Nullable<System.DateTime> fep_PilotingDate { get; set; }
        public Nullable<System.DateTime> fep_LogDate { get; set; }
        public Nullable<int> fep_TargetQty { get; set; }
        public Nullable<int> fep_Qty { get; set; }
    }
}
