//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class fmea_response
    {
        public int responseID { get; set; }
        public Nullable<int> concernID { get; set; }
        public string toolnum { get; set; }
        public string response { get; set; }
        public string pic { get; set; }
        public string photo { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> dateResponse { get; set; }
        public string departmentRes { get; set; }
        public string concernID2 { get; set; }
    }
}
