//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class fmea_concern
    {
        public int concernID { get; set; }
        public string toolnum { get; set; }
        public string concern { get; set; }
        public string stage { get; set; }
        public string statusCon { get; set; }
        public string pic { get; set; }
        public string photo { get; set; }
        public string concernID2 { get; set; }
        public Nullable<System.DateTime> dateConcern { get; set; }
        public string departmentCon { get; set; }
    }
}
