//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class fmea_DCCheck
    {
        public int DCCheckID { get; set; }
        public string toolnum { get; set; }
        public string toynum { get; set; }
        public string paint_ops { get; set; }
        public string nest { get; set; }
        public string others_DC { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> dateDC { get; set; }
    }
}
