//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class fmea_TECheck
    {
        public int TECheckID { get; set; }
        public string toynum { get; set; }
        public string toolnum { get; set; }
        public string runnerType { get; set; }
        public string runnerFrame { get; set; }
        public string runnerVUM { get; set; }
        public string others { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string photo_part { get; set; }
        public string autoDegate { get; set; }
        public string moldType { get; set; }
        public string PA { get; set; }
        public string SW { get; set; }
        public Nullable<System.DateTime> dateTE { get; set; }
    }
}
