//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class fmea_MECheck
    {
        public int MECheckID { get; set; }
        public string toolnum { get; set; }
        public string toynum { get; set; }
        public string jig_ME { get; set; }
        public string area_control_ME { get; set; }
        public string cycle_times { get; set; }
        public string running_type { get; set; }
        public string inhouse_vendor { get; set; }
        public string after_molding_process { get; set; }
        public string others_ME { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> dateME { get; set; }
    }
}
