//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class fmea_QECheck
    {
        public int QECheckID { get; set; }
        public string toolnum { get; set; }
        public string toynum { get; set; }
        public string jig_QE { get; set; }
        public string area_control_QE { get; set; }
        public string legal_marking_QE { get; set; }
        public string func_requirement { get; set; }
        public string func_poundage { get; set; }
        public string abuse_torque_tension { get; set; }
        public string abuse_compression { get; set; }
        public string abuse_drop { get; set; }
        public string life_test_cycle { get; set; }
        public string sharp_edges { get; set; }
        public string projection { get; set; }
        public string entrapment { get; set; }
        public string small_part { get; set; }
        public string small_ball { get; set; }
        public string food_imitation { get; set; }
        public string customer_assy { get; set; }
        public string others_QE { get; set; }
        public Nullable<System.DateTime> dateQE { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string sharp_point { get; set; }
    }
}
