//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class fmea_TACheck
    {
        public int TACheckID { get; set; }
        public string toolnum { get; set; }
        public string toynum { get; set; }
        public string jig_TA { get; set; }
        public string area_control_TA { get; set; }
        public string part_assy { get; set; }
        public string type_of_joint { get; set; }
        public string type_of_fit_joint { get; set; }
        public string use_line_tooling { get; set; }
        public string need_date_code { get; set; }
        public string others_TA { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> dateTA { get; set; }
    }
}
