//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class fmea_PECheck
    {
        public int PECheckID { get; set; }
        public string toolnum { get; set; }
        public string toynum { get; set; }
        public string age_grade { get; set; }
        public string quota { get; set; }
        public string RR { get; set; }
        public Nullable<System.DateTime> DSdate { get; set; }
        public string decoration { get; set; }
        public string VUM { get; set; }
        public string surface_finish { get; set; }
        public string etching { get; set; }
        public string code { get; set; }
        public string legal_marking_PE { get; set; }
        public string logo { get; set; }
        public string hole_tracking { get; set; }
        public string ejector_position { get; set; }
        public string play_pattern { get; set; }
        public string others_PE { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
