//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class IM_Master
    {
        public int ID { get; set; }
        public string IMNum { get; set; }
        public string itemPart { get; set; }
        public string qtyOrder { get; set; }
        public string prfNum { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string approvedBy { get; set; }
        public Nullable<System.DateTime> finishedDate { get; set; }
        public string statusIM { get; set; }
    }
}
