//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class masterTE_sample
    {
        public int ID { get; set; }
        public string toynum { get; set; }
        public string descr { get; set; }
        public string toolnum { get; set; }
        public string APN { get; set; }
        public string RPN { get; set; }
        public string descript { get; set; }
        public string partL { get; set; }
        public string partW { get; set; }
        public string partH { get; set; }
        public string partTHK { get; set; }
        public string Colour { get; set; }
        public string matL { get; set; }
        public string no_toy { get; set; }
        public string cav { get; set; }
        public string toy_week { get; set; }
        public string partType { get; set; }
        public string m_c_Size { get; set; }
        public string cycleTime { get; set; }
        public string noOfSlide { get; set; }
        public string gating { get; set; }
        public string partWeight { get; set; }
        public string material { get; set; }
        public string @class { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string photo_part { get; set; }
    }
}
