//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class mmm_data
    {
        public int ID { get; set; }
        public string mmmRefNum { get; set; }
        public string jobNo { get; set; }
        public string TE { get; set; }
        public string toynum { get; set; }
        public string toolnum { get; set; }
        public string descript { get; set; }
        public string material { get; set; }
        public string devStage { get; set; }
        public string jobMMM { get; set; }
        public string photo { get; set; }
        public string sampleAttached { get; set; }
        public string ModifyAllCav { get; set; }
        public Nullable<System.DateTime> issueDate { get; set; }
        public string division { get; set; }
        public string approvedBy { get; set; }
        public string statusMMM { get; set; }
        public Nullable<System.DateTime> finishedDate { get; set; }
        public string reason { get; set; }
    }
}
