//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ntd_stage
    {
        public int n_stg_ID { get; set; }
        public string n_stg_toy { get; set; }
        public string n_stg_projnum { get; set; }
        public string n_stg_stage { get; set; }
        public Nullable<System.DateTime> n_stg_date { get; set; }
    }
}
