//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ntd_text
    {
        public int n_txt_ID { get; set; }
        public string n_txt_toy { get; set; }
        public string n_txt_cont { get; set; }
        public string n_txt_type { get; set; }
        public Nullable<System.DateTime> n_txt_1stdate { get; set; }
        public Nullable<System.DateTime> n_txt_lastupd { get; set; }
        public string n_txt_usrname { get; set; }
        public byte[] n_txt_projnum { get; set; }
        public string n_txtt_projnum { get; set; }
        public byte[] n_button { get; set; }
        public string n_button_txt { get; set; }
    }
}
