//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ntd_attach
    {
        public int n_att_ID { get; set; }
        public string n_att_toy { get; set; }
        public string n_att_file { get; set; }
        public string n_att_type { get; set; }
        public Nullable<double> n_att_ver { get; set; }
        public Nullable<System.DateTime> n_att_upldate { get; set; }
        public Nullable<System.DateTime> n_att_codate { get; set; }
        public string n_att_stat { get; set; }
        public string n_usrname { get; set; }
        public string n_att_remarks { get; set; }
        public string n_projnum { get; set; }
        public string n_buton { get; set; }
    }
}
