//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class pd_alltoy
    {
        public string pd_projnum { get; set; }
        public string pd_toynum { get; set; }
        public string pd_asstnum { get; set; }
        public string pd_toydesc { get; set; }
        public string pd_segment { get; set; }
        public string pd_toytype { get; set; }
        public string pd_lq { get; set; }
        public Nullable<System.DateTime> pd_ladate { get; set; }
        public string pd_agegrade { get; set; }
        public string pd_comp { get; set; }
        public string pd_season { get; set; }
        public string pd_toyyear { get; set; }
        public string pd_quota { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
