//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class pd_dtm
    {
        public string dtm_proj { get; set; }
        public string dtm_toyn { get; set; }
        public string dtm_skun { get; set; }
        public string dtm_desc { get; set; }
        public string dtm_pena { get; set; }
        public string dtm_fprd { get; set; }
        public Nullable<int> dtm_skuc { get; set; }
        public string dtm_brnd { get; set; }
        public string dtm_seas { get; set; }
        public string dtm_path { get; set; }
        public Nullable<int> dtm_lice { get; set; }
        public string dtm_type { get; set; }
        public string dtm_espm { get; set; }
        public string dtm_esdg { get; set; }
        public string dtm_modg { get; set; }
        public string dtm_desg { get; set; }
        public string dtm_plcs { get; set; }
        public string dtm_hair { get; set; }
        public string dtm_hdpf { get; set; }
        public string dtm_hdpa { get; set; }
        public string dtm_text { get; set; }
        public string dtm_soft { get; set; }
        public string dtm_sgdv { get; set; }
        public string dtm_tool { get; set; }
        public string dtm_mect { get; set; }
        public string dtm_mpkg { get; set; }
        public string dtm_mpkd { get; set; }
        public string dtm_ppkg { get; set; }
        public Nullable<double> dtm_xfty { get; set; }
        public Nullable<double> dtm_cost { get; set; }
        public Nullable<System.DateTime> dtm_laun { get; set; }
        public string dtm_laqu { get; set; }
        public string dtm_quot { get; set; }
        public string dtm_runr { get; set; }
        public Nullable<System.DateTime> dtm_dsps { get; set; }
        public Nullable<System.DateTime> dtm_dsfs { get; set; }
        public Nullable<System.DateTime> dtm_dsfa { get; set; }
        public string dtm_dsac { get; set; }
        public Nullable<System.DateTime> dtm_dtos { get; set; }
        public Nullable<System.DateTime> dtm_dtoa { get; set; }
        public string dtm_dtac { get; set; }
        public Nullable<System.DateTime> dtm_kick { get; set; }
        public Nullable<System.DateTime> dtm_bomi { get; set; }
        public Nullable<System.DateTime> dtm_fcin { get; set; }
        public Nullable<System.DateTime> dtm_fces { get; set; }
        public Nullable<System.DateTime> dtm_fcea { get; set; }
        public string dtm_fcac { get; set; }
        public Nullable<System.DateTime> dtm_crcs { get; set; }
        public Nullable<System.DateTime> dtm_crca { get; set; }
        public string dtm_crac { get; set; }
        public Nullable<System.DateTime> dtm_crss { get; set; }
        public Nullable<System.DateTime> dtm_crsa { get; set; }
        public string dtm_csaa { get; set; }
        public Nullable<System.DateTime> dtm_crms { get; set; }
        public Nullable<System.DateTime> dtm_crma { get; set; }
        public string dtm_crmc { get; set; }
        public Nullable<System.DateTime> dtm_fpcs { get; set; }
        public Nullable<System.DateTime> dtm_fpca { get; set; }
        public string dtm_fpac { get; set; }
        public Nullable<System.DateTime> dtm_fpss { get; set; }
        public Nullable<System.DateTime> dtm_fpsa { get; set; }
        public string dtm_fpaa { get; set; }
        public Nullable<System.DateTime> dtm_fpms { get; set; }
        public Nullable<System.DateTime> dtm_fpma { get; set; }
        public string dtm_fpmc { get; set; }
        public string dtm_stat { get; set; }
        public string dtm_note { get; set; }
        public string dtm_comp { get; set; }
        public Nullable<int> dtm_cosi { get; set; }
        public string dtm_rema { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
