//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class pd_issues
    {
        public int iss_ID { get; set; }
        public string iss_issue { get; set; }
        public string iss_stage { get; set; }
        public string iss_status { get; set; }
        public Nullable<System.DateTime> iss_opendate { get; set; }
        public string iss_openby { get; set; }
        public Nullable<System.DateTime> iss_closedate { get; set; }
        public string iss_closeby { get; set; }
        public string pd_projnum { get; set; }
    }
}
