//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class pd_input
    {
        public int i_id { get; set; }
        public string i_toy { get; set; }
        public string i_desc { get; set; }
        public string i_PE { get; set; }
        public string i_accy { get; set; }
        public Nullable<System.DateTime> i_feppaint { get; set; }
        public Nullable<System.DateTime> i_approved { get; set; }
        public string i_dstatus { get; set; }
        public string i_molded { get; set; }
        public string i_operation { get; set; }
        public Nullable<System.DateTime> i_asample { get; set; }
        public Nullable<System.DateTime> i_1sub { get; set; }
    }
}
