//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class pd_meeting
    {
        public int me_ID { get; set; }
        public string me_update { get; set; }
        public string me_area { get; set; }
        public Nullable<System.DateTime> me_date { get; set; }
        public string me_user { get; set; }
        public string pd_projnum { get; set; }
    }
}
