//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class pd_notes
    {
        public int not_ID { get; set; }
        public string not_remarks { get; set; }
        public string not_stage { get; set; }
        public Nullable<System.DateTime> not_date { get; set; }
        public string not_user { get; set; }
        public string pd_projnum { get; set; }
    }
}
