//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class pd_skintone
    {
        public int sk_ID { get; set; }
        public string sk_name { get; set; }
        public string sk_code { get; set; }
        public string sk_actv { get; set; }
    }
}
