//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class pd_schedule
    {
        public int sch_id { get; set; }
        public string sch_projnum { get; set; }
        public string sch_pe { get; set; }
        public string sch_toydesc { get; set; }
        public string sch_asstnum { get; set; }
        public string sch_attr { get; set; }
        public string sch_task { get; set; }
        public Nullable<System.DateTime> sch_date { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
