//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class pd_torsotype
    {
        public int trs_ID { get; set; }
        public string trs_name { get; set; }
        public string trs_type { get; set; }
        public Nullable<int> sw_charID { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
