//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class pd_user
    {
        public string us_KPK { get; set; }
        public string us_NAME { get; set; }
        public string us_usrname { get; set; }
        public string us_email { get; set; }
        public string us_pwd { get; set; }
        public Nullable<int> grp_ID { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public string us_stat { get; set; }
        public string Role { get; set; }
    }
}
