//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintReq
    {
        public int requestID { get; set; }
        public string toyNum { get; set; }
        public string descript { get; set; }
        public string toolNum { get; set; }
        public string requestFor { get; set; }
        public string materialAct { get; set; }
        public string suggMaterial { get; set; }
        public Nullable<System.DateTime> requestDate { get; set; }
        public string targetDate { get; set; }
        public string progress { get; set; }
        public string requestor { get; set; }
        public string kpk { get; set; }
        public string division { get; set; }
        public string linkConvert { get; set; }
        public string qty { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string volumeMaterial { get; set; }
        public Nullable<int> scoring { get; set; }
        public string size { get; set; }
    }
}
