//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptmi_tools
    {
        public string pt_toolnum { get; set; }
        public string pt_desc { get; set; }
        public string pt_from { get; set; }
        public Nullable<System.DateTime> pt_recdate { get; set; }
        public string pt_delivto { get; set; }
        public string pt_loc { get; set; }
        public string pt_actvt { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
