//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class rc_sculpt
    {
        public string rc_num { get; set; }
        public string rc_name { get; set; }
        public string rc_actvt { get; set; }
        public Nullable<System.DateTime> rc_adddate { get; set; }
        public string rc_addby { get; set; }
    }
}
