//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class rc_variant
    {
        public string rcv_ipn { get; set; }
        public string rcv_agile { get; set; }
        public string rcv_toy { get; set; }
        public string rcv_desc { get; set; }
        public string rcv_user { get; set; }
        public Nullable<System.DateTime> rcv_date { get; set; }
        public string rcv_rmrk { get; set; }
        public string rcv_hard { get; set; }
        public string rc_num { get; set; }
        public Nullable<int> sk_ID { get; set; }
    }
}
