//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_meth
    {
        public int sw_methID { get; set; }
        public string sw_methOp { get; set; }
        public string sw_methMC { get; set; }
        public string sw_code { get; set; }
        public float sw_methHrs { get; set; }
        public int sw_sptID { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual sw_spt sw_spt { get; set; }
    }
}
