//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_method
    {
        public int sw_methID { get; set; }
        public Nullable<double> sw_G01 { get; set; }
        public Nullable<double> sw_G02 { get; set; }
        public Nullable<double> sw_G03 { get; set; }
        public Nullable<int> sw_sptID { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
