//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_pat
    {
        public int sw_patID { get; set; }
        public string sw_patName { get; set; }
        public double sw_patP { get; set; }
        public double sw_dieCut { get; set; }
        public int sw_sptID { get; set; }
        public System.DateTime updated_at { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual sw_spt sw_spt { get; set; }
    }
}
