//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_pict
    {
        public int sw_pID { get; set; }
        public string sw_pFile { get; set; }
        public Nullable<int> sw_sptID { get; set; }
        public Nullable<short> sw_img_thumb { get; set; }
        public Nullable<System.DateTime> sw_pUpdate { get; set; }
    }
}
