//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_spt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sw_spt()
        {
            this.sw_meth = new HashSet<sw_meth>();
            this.sw_pat = new HashSet<sw_pat>();
        }
    
        public int sw_sptID { get; set; }
        public string sw_sptName { get; set; }
        public string sw_sptPhoto { get; set; }
        public string sw_sptPatPhoto { get; set; }
        public string sw_sptToyRef { get; set; }
        public string sw_sptExcl { get; set; }
        public int sw_charID { get; set; }
        public int sw_spID { get; set; }
        public string sw_FbType { get; set; }
        public System.DateTime updated_at { get; set; }
        public System.DateTime created_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sw_meth> sw_meth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sw_pat> sw_pat { get; set; }
    }
}
