//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_ToolTf
    {
        public int ID_PE { get; set; }
        public string toynum { get; set; }
        public string moldnum { get; set; }
        public string descript { get; set; }
        public Nullable<System.DateTime> submit_date { get; set; }
        public string location_tf { get; set; }
        public string PE { get; set; }
        public string project_path { get; set; }
        public Nullable<System.DateTime> FEP_date { get; set; }
        public Nullable<System.DateTime> EEP { get; set; }
        public string stts_approve { get; set; }
        public string stts_material { get; set; }
        public string detail { get; set; }
        public string comment { get; set; }
    }
}
