//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_ToolTf_Mtrl_Apprv
    {
        public int ID { get; set; }
        public string ID_PE { get; set; }
        public Nullable<System.DateTime> CEP { get; set; }
        public string stts_material { get; set; }
        public string comment { get; set; }
    }
}
