//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_ToolTf_Checklist
    {
        public int ID { get; set; }
        public string ID_PE { get; set; }
        public string legal_mark { get; set; }
        public string plate_mold { get; set; }
        public string aluminium_mold { get; set; }
        public string mold_w_heater { get; set; }
        public string stts_approve { get; set; }
        public string detail { get; set; }
    }
}
