//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rustammm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toolreq
    {
        public int ID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date_Request { get; set; }
        public string Tool_Requested { get; set; }
        public string Description { get; set; }
        public int Qty_ { get; set; }
        public System.DateTime Date_Needed { get; set; }
        public Nullable<System.DateTime> Date_Done { get; set; }
        public string Reference { get; set; }
        public string Handle_by { get; set; }
        public string Toy_Number { get; set; }
        public string Requestor { get; set; }
        public string Purpose { get; set; }
        public string Category { get; set; }
        public string Sculpt_Mold_Number { get; set; }
    }
}
